server:
  port: 8085

spring:
  profiles:
    active: dev
    include: website,alipay,oss
  data:
    redis:
      #Redis服务器IP
      host: ${REDIS_HOST}
      #Redis服务器连接端口
      port: ${REDIS_PORT}
      #Redis服务器连接密码
      password: ${REDIS_PASSWORD}
      #连接超时时间（毫秒）
      timeout: 10000

pic:
  save:
    #图片保存方式, 1不保存，使用网络图片 ，2本地保存
    type: 2
    #图片保存路径
    path: /app/pic


#模版配置
templates:
  name: dark

#小说内容保存配置
content:
  save:
    storage: db # 小说内容存储方式：db-数据库，txt-TXT文本
    path: /app/books  # 小说TXT文本保存路径

# HTTP 代理配置
http:
  proxy:
    # 是否开启 HTTP 代理，true-开启，false-不开启
    enabled: false
    # 代理 IP
    ip: proxy.bestproxy.com
    # 代理端口号
    port: 2312
    # 代理用户名
    username: bestproxy_u
    # 代理密码
    password: bestproxy_p

jwt:
  secret: novel!#20191230
  expiration: 604800

#缓存管理密码
cache:
  manager:
    password: novel@2020117


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接 （多个用逗号分隔）
  urlPatterns: /book/addCommentReply,/book/addBookComment,/user/addFeedBack,/author/addBook,/author/addBookContent,/author/updateBookContent,/author/register.html


author:
  income:
    #税率(扣税后所得比率)
    tax-rate: 0.9
    #分佣比例
    share-proportion: 0.7
    #兑换比率(人民币)
    exchange-proportion: 0.01

#小说章节定价规则
book:
  price:
    #字数
    word-count: 1000
    #价值(屋币)
    value: 5


--- #--------------------- Spring AI 配置----------------------
spring:
  ai:
    openai:
      image:
        enabled: true
        base-url: https://api.siliconflow.cn
        api-key: sk-jjtixmivxaccndqgkqfkbgkzvmbctdxogcrfbjzfttbouitt
        options:
          model: Kwai-Kolors/Kolors
          response_format: URL
      api-key: sk-jjtixmivxaccndqgkqfkbgkzvmbctdxogcrfbjzfttbouitt
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B


