services:
  novel-db:
    container_name: novel-db
    image: mysql:8.0
    restart: always
    hostname: novel-db
    environment:
      - MYSQL_ROOT_PASSWORD=${password}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./share/novel_plus.sql:/docker-entrypoint-initdb.d/init.sql
      - ./share:/share
    command: mysqld --max_allowed_packet=100M
    ports:
      - "3306:33060"
    networks:
      - novelnet

  novel-redis:
    container_name: novel-redis
    image: redis:7.0
    restart: always
    hostname: novel-redis
    command: redis-server --save 60 1 --loglevel warning --requirepass "${redispwd}"
    ports:
      - "6379:6379"
    networks:
      - novelnet

  front:
    container_name: novel-front
    image: openjdk:21
    restart: always
    environment:
      - dburl=${dburl}
      - username=${username}
      - password=${password}
      - redishost=${redishost}
      - redispwd=${redispwd}
      - redisport=${redisport}
    volumes:
      - ./front:/app/front
      - ./download/books:/app/books
      - ./download/pic:/app/pic
    working_dir: /app/front
    command: sh -c "java -jar -Dspring.profiles.active=dev /app/front/novel-front.jar"
    ports:
      - 8581:8085
    depends_on:
      - novel-db
      - novel-redis
    networks:
      - novelnet

  admin:
    container_name: novel-admin
    image: openjdk:21
    restart: always
    environment:
      - dburl=${dburl}
      - username=${username}
      - password=${password}
      - redishost=${redishost}
      - redispwd=${redispwd}
      - redisport=${redisport}
    volumes:
      - ./admin:/app/admin
      - ./download/books:/app/books
      - ./download/pic:/app/pic
    working_dir: /app/admin
    command: sh -c "java -jar -Dspring.profiles.active=dev /app/admin/novel-admin.jar"
    ports:
      - 8582:8088
    depends_on:
      - novel-db
      - novel-redis
    networks:
      - novelnet

  # crawler1:
  #   container_name: novel-crawl1
  #   image: openjdk:21
  #   restart: always
  #   environment:
  #     - dburl=${dburl}
  #     - username=${username}
  #     - password=${password}
  #   volumes:
  #     - ./novel-crawl/target/build:/app/crawl
  #     - ./novel-crawl/target/build/config:/config
  #     - ./docker/download/books:/app/books
  #     - ./docker/download/pic:/app/pic
  #   command: sh -c "java -jar -Dspring.profiles.active=dev /app/crawl/novel-crawl.jar"
  #   ports:
  #     - 8583:8083
  #   depends_on:
  #     - novel-db
  #     - novel-redis
  #   networks:
  #     - novelnet

  crawler2:
    container_name: novel-crawl2
    image: openjdk:21
    restart: always
    environment:
      - dburl=${dburl}
      - username=${username}
      - password=${password}
    volumes:
      - ./crawl2:/app
      - ./h2db:/app/db
      - ./download:/app/download
    working_dir: /app
    command: java -jar -Dspring.profiles.active=dev /app/novel-crawl2.jar
    ports:
      - 8584:30000
    depends_on:
      - novel-db
    networks:
      - novelnet

networks:
  novelnet:
    driver: bridge
    # driver_opts:
    #   com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
