proxy_set_header    Host                $host;
proxy_set_header    X-Real-IP           $remote_addr;
proxy_set_header    X-Forwarded-Host    $host;
proxy_set_header    X-Forwarded-Server  $host;
proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;

location / {
    proxy_pass  http://localhost:8581/;

    auth_basic "WDLL Literature";
    auth_basic_user_file /etc/nginx/.htpasswd_wdll;
}
