spring:
  application:
   name: novelDownloadServer
  profiles:
    active: prod
  app:
    #图片保存路径
    coverPath: pic/localPic
    coverUrlPrefix: /localPic
    bookUrlPrefix: /book

server:
  port: 30000
